branches:
  - master
repositoryUrl: https://github.com/sarthakjdev/wapi.go
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
