name: Release

on:
  push:
    branches:
      - master

concurrency:
  group: check-pr-title-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      
